<?php
/**
 * Asset loading helper functions
 * 
 * Generated automatically by webpack.mix.js
 * Do not edit this file directly
 */

/**
 * Get the versioned asset URL
 *
 * @param string $path Asset path relative to theme root
 * @return string Versioned asset URL
 */
function aqualuxe_asset($path) {
    static $manifest = null;
    
    if (is_null($manifest)) {
        $manifestPath = get_template_directory() . '/assets/assets-manifest.json';
        
        if (file_exists($manifestPath)) {
            $manifest = json_decode(file_get_contents($manifestPath), true);
        } else {
            $manifest = [];
        }
    }
    
    $path = ltrim($path, '/');
    
    if (isset($manifest[$path])) {
        return get_template_directory_uri() . '/' . $manifest[$path];
    }
    
    return get_template_directory_uri() . '/' . $path;
}

/**
 * Print the versioned asset URL
 *
 * @param string $path Asset path relative to theme root
 * @return void
 */
function aqualuxe_asset_url($path) {
    echo esc_url(aqualuxe_asset($path));
}

/**
 * Get critical CSS for a specific template
 *
 * @param string $template Template name (home, blog, shop, product)
 * @return string Critical CSS content
 */
function aqualuxe_get_critical_css($template) {
    $critical_css_path = get_template_directory() . '/assets/css/critical/' . $template . '.css';
    
    if (file_exists($critical_css_path)) {
        return file_get_contents($critical_css_path);
    }
    
    return '';
}

/**
 * Print critical CSS inline
 *
 * @param string $template Template name (home, blog, shop, product)
 * @return void
 */
function aqualuxe_critical_css($template) {
    $critical_css = aqualuxe_get_critical_css($template);
    
    if (!empty($critical_css)) {
        echo '<style id="aqualuxe-critical-css">' . $critical_css . '</style>';
    }
}