/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './*.php',
    './inc/**/*.php',
    './templates/**/*.php',
    './template-parts/**/*.php',
    './src/js/**/*.js',
  ],
  safelist: [
    'rtl',
    'home',
    'blog',
    'archive',
    'single',
    'page',
    'search',
    'error404',
    'logged-in',
    'admin-bar',
    'no-customize-support',
    'wp-embed-responsive',
    'woocommerce',
    'woocommerce-page',
    'woocommerce-js',
    'woocommerce-no-js',
    'woocommerce-active',
    'woocommerce-demo-store',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#0073aa',
          50: '#e6f3f8',
          100: '#cce7f1',
          200: '#99cfe3',
          300: '#66b7d5',
          400: '#339fc7',
          500: '#0073aa',
          600: '#005c88',
          700: '#004566',
          800: '#002e44',
          900: '#001722',
        },
        secondary: {
          DEFAULT: '#23282d',
          50: '#e9eaeb',
          100: '#d3d5d7',
          200: '#a7acaf',
          300: '#7b8287',
          400: '#4f595f',
          500: '#23282d',
          600: '#1c2024',
          700: '#15181b',
          800: '#0e1012',
          900: '#070809',
        },
        accent: {
          DEFAULT: '#00a0d2',
          50: '#e6f7fc',
          100: '#cceff9',
          200: '#99dff3',
          300: '#66cfed',
          400: '#33bfe7',
          500: '#00a0d2',
          600: '#0080a8',
          700: '#00607e',
          800: '#004054',
          900: '#00202a',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        serif: ['Merriweather', 'Georgia', 'serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
      },
      spacing: {
        '128': '32rem',
        '144': '36rem',
      },
      borderRadius: {
        'sm': '0.125rem',
        DEFAULT: '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      boxShadow: {
        'soft': '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
        'card': '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
      },
      typography: (theme) => ({
        DEFAULT: {
          css: {
            color: theme('colors.secondary.700'),
            a: {
              color: theme('colors.primary.500'),
              '&:hover': {
                color: theme('colors.primary.700'),
              },
            },
            h1: {
              color: theme('colors.secondary.900'),
            },
            h2: {
              color: theme('colors.secondary.900'),
            },
            h3: {
              color: theme('colors.secondary.900'),
            },
            h4: {
              color: theme('colors.secondary.900'),
            },
            blockquote: {
              borderLeftColor: theme('colors.primary.500'),
            },
            'ul > li::before': {
              backgroundColor: theme('colors.primary.500'),
            },
            'ol > li::before': {
              color: theme('colors.primary.500'),
            },
          },
        },
      }),
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/aspect-ratio'),
    require('@tailwindcss/line-clamp'),
  ],
  darkMode: 'class',
};