<?php
/**
 * Asset loading helper functions
 * 
 * Generated automatically by webpack.mix.js
 * Do not edit this file directly
 */

/**
 * Get the versioned asset URL
 *
 * @param string $path Asset path relative to theme root
 * @return string Versioned asset URL
 */
function aqualuxe_asset($path) {
    static $manifest = null;
    
    if (is_null($manifest)) {
        $manifestPath = get_template_directory() . '/assets/assets-manifest.json';
        
        if (file_exists($manifestPath)) {
            $manifest = json_decode(file_get_contents($manifestPath), true);
        } else {
            $manifest = [];
        }
    }
    
    $path = ltrim($path, '/');
    
    if (isset($manifest[$path])) {
        return get_template_directory_uri() . '/' . $manifest[$path];
    }
    
    return get_template_directory_uri() . '/' . $path;
}

/**
 * Print the versioned asset URL
 *
 * @param string $path Asset path relative to theme root
 * @return void
 */
function aqualuxe_asset_url($path) {
    echo esc_url(aqualuxe_asset($path));
}

/**
 * Get critical CSS for a specific template
 *
 * @param string $template Template name (home, blog, shop, product)
 * @return string Critical CSS content
 */
function aqualuxe_get_critical_css($template) {
    $critical_css_path = get_template_directory() . '/assets/css/critical/' . $template . '.css';
    
    if (file_exists($critical_css_path)) {
        return file_get_contents($critical_css_path);
    }
    
    return '';
}

/**
 * Print critical CSS inline
 *
 * @param string $template Template name (home, blog, shop, product)
 * @return void
 */
function aqualuxe_critical_css($template) {
    $critical_css = aqualuxe_get_critical_css($template);
    
    if (!empty($critical_css)) {
        echo '<style id="aqualuxe-critical-css">' . $critical_css . '</style>';
    }
}

/**
 * Enqueue theme styles
 *
 * @return void
 */
function aqualuxe_enqueue_styles() {
    // Enqueue main stylesheet
    wp_enqueue_style(
        'aqualuxe-style',
        aqualuxe_asset('assets/css/main.css'),
        [],
        null
    );
    
    // Enqueue print stylesheet
    wp_enqueue_style(
        'aqualuxe-print',
        aqualuxe_asset('assets/css/print.css'),
        [],
        null,
        'print'
    );
    
    // Enqueue dark mode stylesheet
    wp_enqueue_style(
        'aqualuxe-dark-mode',
        aqualuxe_asset('assets/css/dark-mode.css'),
        ['aqualuxe-style'],
        null
    );
    
    // Enqueue WooCommerce stylesheet if WooCommerce is active
    if (class_exists('WooCommerce')) {
        wp_enqueue_style(
            'aqualuxe-woocommerce',
            aqualuxe_asset('assets/css/woocommerce.css'),
            ['aqualuxe-style'],
            null
        );
    }
}

/**
 * Enqueue theme scripts
 *
 * @return void
 */
function aqualuxe_enqueue_scripts() {
    // Enqueue vendor scripts
    wp_enqueue_script(
        'aqualuxe-vendor',
        aqualuxe_asset('assets/js/vendor.js'),
        [],
        null,
        true
    );
    
    // Enqueue main scripts
    wp_enqueue_script(
        'aqualuxe-app',
        aqualuxe_asset('assets/js/app.js'),
        ['aqualuxe-vendor'],
        null,
        true
    );
    
    // Enqueue lazy loading script
    wp_enqueue_script(
        'aqualuxe-lazy-loading',
        aqualuxe_asset('assets/js/lazy-loading.js'),
        ['aqualuxe-app'],
        null,
        true
    );
    
    // Enqueue service worker registration script
    wp_enqueue_script(
        'aqualuxe-service-worker',
        aqualuxe_asset('assets/js/service-worker-register.js'),
        [],
        null,
        true
    );
    
    // Enqueue WooCommerce script if WooCommerce is active
    if (class_exists('WooCommerce')) {
        wp_enqueue_script(
            'aqualuxe-woocommerce',
            aqualuxe_asset('assets/js/woocommerce.js'),
            ['aqualuxe-app', 'jquery'],
            null,
            true
        );
        
        // Localize WooCommerce script
        wp_localize_script('aqualuxe-woocommerce', 'aqualuxe_params', [
            'ajax_url' => admin_url('admin-ajax.php'),
            'wc_ajax_url' => WC_AJAX::get_endpoint('%%endpoint%%'),
            'quick_view_nonce' => wp_create_nonce('aqualuxe-quick-view'),
            'wishlist_nonce' => wp_create_nonce('aqualuxe-wishlist'),
            'filter_nonce' => wp_create_nonce('aqualuxe-filter'),
            'currency_symbol' => get_woocommerce_currency_symbol(),
            'currency_format' => get_option('woocommerce_price_format', '{symbol}{price}'),
        ]);
    }
    
    // Add comment reply script if needed
    if (is_singular() && comments_open() && get_option('thread_comments')) {
        wp_enqueue_script('comment-reply');
    }
}

/**
 * Add preload tags for critical assets
 *
 * @return void
 */
function aqualuxe_preload_assets() {
    // Preload main font files
    echo '<link rel="preload" href="' . esc_url(aqualuxe_asset('assets/fonts/montserrat-v25-latin-regular.woff2')) . '" as="font" type="font/woff2" crossorigin>';
    echo '<link rel="preload" href="' . esc_url(aqualuxe_asset('assets/fonts/montserrat-v25-latin-700.woff2')) . '" as="font" type="font/woff2" crossorigin>';
    echo '<link rel="preload" href="' . esc_url(aqualuxe_asset('assets/fonts/playfair-display-v30-latin-regular.woff2')) . '" as="font" type="font/woff2" crossorigin>';
    
    // Preload logo
    echo '<link rel="preload" href="' . esc_url(aqualuxe_asset('assets/images/logo.svg')) . '" as="image">';
    
    // Preconnect to external domains
    echo '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>';
    
    // DNS prefetch
    echo '<link rel="dns-prefetch" href="//fonts.googleapis.com">';
    echo '<link rel="dns-prefetch" href="//fonts.gstatic.com">';
    echo '<link rel="dns-prefetch" href="//ajax.googleapis.com">';
}

/**
 * Add defer attribute to non-critical scripts
 *
 * @param string $tag The script tag.
 * @param string $handle The script handle.
 * @return string Modified script tag.
 */
function aqualuxe_defer_scripts($tag, $handle) {
    // List of scripts to defer
    $defer_scripts = [
        'aqualuxe-lazy-loading',
        'aqualuxe-service-worker',
    ];
    
    if (in_array($handle, $defer_scripts, true)) {
        return str_replace(' src', ' defer src', $tag);
    }
    
    return $tag;
}

/**
 * Add async attribute to non-critical scripts
 *
 * @param string $tag The script tag.
 * @param string $handle The script handle.
 * @return string Modified script tag.
 */
function aqualuxe_async_scripts($tag, $handle) {
    // List of scripts to async
    $async_scripts = [
        'aqualuxe-service-worker',
    ];
    
    if (in_array($handle, $async_scripts, true)) {
        return str_replace(' src', ' async src', $tag);
    }
    
    return $tag;
}

/**
 * Add preload attribute to critical styles
 *
 * @param string $tag The link tag.
 * @param string $handle The style handle.
 * @return string Modified link tag.
 */
function aqualuxe_preload_styles($tag, $handle) {
    // List of styles to preload
    $preload_styles = [
        'aqualuxe-style',
    ];
    
    if (in_array($handle, $preload_styles, true)) {
        return str_replace(' rel="stylesheet"', ' rel="preload" as="style" onload="this.onload=null;this.rel=\'stylesheet\'"', $tag);
    }
    
    return $tag;
}

/**
 * Add hooks for asset loading
 */
add_action('wp_enqueue_scripts', 'aqualuxe_enqueue_styles');
add_action('wp_enqueue_scripts', 'aqualuxe_enqueue_scripts');
add_action('wp_head', 'aqualuxe_preload_assets', 1);
add_filter('script_loader_tag', 'aqualuxe_defer_scripts', 10, 2);
add_filter('script_loader_tag', 'aqualuxe_async_scripts', 10, 2);
add_filter('style_loader_tag', 'aqualuxe_preload_styles', 10, 2);